version: "3.8"

services:
  backend:
    build: ./backend
    image: backtest-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
    depends_on:
      - redis
    volumes:
      - ./backend:/app
    # network_mode: host
  redis:
    image: redis:6.2-alpine
    volumes:
      - redis-data:/data
    command: redis-server --requirepass 1q2w3e4r! --disable-command CONFIG
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
